
name: Auto Close Labeled Issues

on:
  issues:
    types: [labeled]

jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Close issues with specific labels
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const issueLabel = context.payload.label.name;
          if (issueLabel === 'completed' || issueLabel === 'wontfix') {
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });
          }
