name: Close Labeled Issues
on:
  issues:
    types:
      - labeled
jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close issue
        uses: actions/close-issue@v4
        with:
          labels: completed,wontfix
          comment: 'This issue was automatically closed because it was labeled as "completed" or "wontfix".'
